version: '3.9'
services:
  app:
    build: .
    image: laravel-micro:dev
    env_file: .env
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "php -r 'exit(file_exists(\"/var/www/html/storage/logs/laravel.log\")?0:0);' "]
      interval: 30s
      timeout: 5s
      retries: 3

  web:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

networks:
  default:
    driver: bridge

